---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Rocky)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.2/terraform_1.3.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
      

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Debian servers
    tags: apache,apache2,ubuntu,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_virtualization_type == "virtualbox" and ansible_distribution == "Debian"

  - name: install apache and php for Rocky servers
    tags: apache,httpd,rocky
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_virtualization_type == "virtualbox" and ansible_distribution == "Rocky"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Rocky)
    tags: mariadb,db,rocky,debian
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Debian)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:

    - name : install samba package
      tags: samba
      package:
        name : samba
        state : latest


