- name: install apache and php for Debian servers
  tags: apache,apache2,ubuntu,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_virtualization_type == "virtualbox" and ansible_distribution == "Debian"

- name: install apache and php for Rocky servers
  tags: apache,httpd,rocky
  dnf:
    name: 
      - httpd
      - php
    state: latest
  when: ansible_virtualization_type == "virtualbox" and ansible_distribution == "Rocky"

- name: start httpd (Rocky)
  tags: apache, rocky, centos, httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_virtualization_type == "virtualbox" and ansible_distribution == "Rocky"

- name: change email address for admin
  tags: apache, centos, httpd, rocky
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Rocky"
  register: httpd_var

- name: restart httpd (Rocky)
  tags: apache, centos, rocky, httpd
  service:
    name: httpd
    state: restarted
  when: httpd_var.changed

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644